name       : love
version    : 0.10.2
release    : 3
source     :
    - https://bitbucket.org/rude/love/downloads/love-0.10.2-linux-src.tar.gz : b26b306b113158927ae12d2faadb606eb1db49ffdcd7592d6a0a3fc0af21a387
license    :
    - Libpng
    - Zlib
summary    : Lua 2D Game Engine
component  : programming.tools
description: |
    An open-source 2D game engine which uses the versatile Lua scripting language to create dynamic gaming experiences
libsplit   : no
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - pkgconfig(zlib)
    - physfs-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
