name       : love
version    : '11.1'
release    : 6
source     :
    - https://bitbucket.org/rude/love/downloads/love-11.1-linux-src.tar.gz : bc5e9a70021de830f1032d6afe900f0b81902e2b6c610e26cf1d6859bf8e7cde
license    :
    - Libpng
    - Zlib
summary    : Lua 2D Game Engine
component  : programming.tools
description: |
    An open-source 2D game engine which uses the versatile Lua scripting language to create dynamic gaming experiences
libsplit   : no
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - pkgconfig(zlib)
    - physfs-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
