name       : love
version    : '11.4'
release    : 16
source     :
    - https://github.com/love2d/love/releases/download/11.4/love-11.4-linux-src.tar.gz : e32feecaf5f4f210242a4b5f26cdf9ce9014bfde18d51286f643bb7fe51f5369
homepage   : https://love2d.org/
license    :
    - Libpng
    - Zlib
component  : programming.tools
summary    : LÖVE is an awesome 2D game framework for Lua
description: |
    LÖVE is a framework for making 2D games in the Lua programming language. It is totally free, and can be used in anything from friendly open-source hobby projects, to evil, closed-source commercial ones.
libsplit   : no
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(physfs)
    - pkgconfig(sdl2)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
