name       : love
version    : 0.10.1
release    : 2
source     :
    - https://bitbucket.org/rude/love/downloads/love-0.10.1-linux-src.tar.gz : a2b0c9a1096a064c40f9f4bafd7ee92c0aa64f70146f7574992425c24e4541fb
license    :
    - Libpng
    - Zlib
summary    : Lua 2D Game Engine
component  : programming.tools
description: |
    An open-source 2D game engine which uses the versatile Lua scripting language to create dynamic gaming experiences
libsplit   : no
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - pkgconfig(zlib)
    - physfs-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
