name       : love
version    : '11.3'
release    : 15
source     :
    - https://github.com/love2d/love/releases/download/11.3/love-11.3-linux-src.tar.gz : 649f0db7750ca121e4de7b60208703661052356df35f4cfad490b1ba14dd1455
homepage   : https://love2d.org/
license    :
    - Libpng
    - Zlib
summary    : Lua 2D Game Engine
component  : programming.tools
description: |
    An open-source 2D game engine which uses the versatile Lua scripting language to create dynamic gaming experiences
libsplit   : no
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpg123)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - physfs-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
